### ISSUE TITLE
Call Service Node does not work with with "cast" domain since upgrade to 11 (incl. 11.01)

### ISSUE THREAD

**Issue by matbox** [hassio-addons/addon-node-red#1287]
# Problem/Motivation
Since the update to 11, my casting automations don't work anymore. It looks as if the update changed the way entities are handed to the service, rendering it incompatible with what the cast domain expects.

## Expected behavior
I did not expect any change after the update. 

## Actual behavior
Setting up a call-service node to show a lovelace view on my Android TV devices does not work anymore. The API errors out with "Call-service error. value should be a string for dictionary value @ data['entity_id']"

## Steps to reproduce
Set up a new call-service node to cast a dashboard to a Chromecast Device.

## Proposed changes
No clue. Looks like a way to define the entity as a string instead of the now-default(?) of array would fix the issue.

**Comment by tlalos** [comment]
same issue here

**Comment by zachowj** [comment]
This isn't an add-on issue and should be reported to the HA nodes repo so it can be tracked. <https://github.com/zachowj/node-red-contrib-home-assistant-websocket>

The actual issue is that HA accepts entity id as a string but converts it to an array before passing it to the called service. If you turn on debugging for the call-service node you'll see that NR is actually sending the entity_id as a string to HA.

A temporary fix for this is the add `entity_id` to the data field `{"entity_id": "media_player.chromecast"}` and remove it from the entity field.

**Comment by matbox** [comment]
Hi @zachowj, 

Thanks for your comment. I will report it in the right repo. Sadly the workaround is not possible as Node Red does not seem to keep the entity field actually empty. The error is the same when adding the entity_id to data and when editing the node again the entity is (additionally) back as a selection in the Entity section.

**Comment by matbox** [comment]
Ah! That works indeed. Thank you for the hint! I'm closing this issue as the issue would not get addressed in the add-on.
