### ISSUE TITLE
Node-RED Exec Node Fails to Run Local Executable File

### ISSUE THREAD

**Issue by matata86** [hassio-addons/addon-node-red#1750]
# Problem/Motivation

> I've encountered an issue where the `exec` node in Node-RED, which previously functioned correctly, has stopped working in the last week to ten days. This node is supposed to execute a local executable file.

## Expected behavior

> I expected the `exec` node to successfully run the local executable file located at `/config/3rdparty/speedtest/speedtest --format=json --accept-license --accept-gdpr`.

## Actual behavior

> The execution of the file through the `exec` node fails, and the message payload shows an error: `/bin/bash: line 1: /config/3rdparty/speedtest/speedtest: No such file or directory`. However, when the same command is run through the terminal addon, it works as expected. This indicates that the file does exist and is accessible.

## Steps to reproduce

1. Use the `exec` node in Node-RED to run the command `/config/3rdparty/speedtest/speedtest --format=json --accept-license --accept-gdpr`.
2. Observe the error in the debug output of Node-RED.

## Proposed changes

> I don't have a specific workaround or fix for this issue. It seems to be related to how the `exec` node accesses or executes local files, which has changed or is not functioning as it used to. Any insights or solutions to this problem would be greatly appreciated.

Additional Information: I am using version 16.0.2 of the Node-RED addon.

![1](https://github.com/hassio-addons/addon-node-red/assets/28623294/e6d3cb96-9ffd-4879-8b94-4986c1e0da49)

![2](https://github.com/hassio-addons/addon-node-red/assets/28623294/e2dd5694-0700-4845-85b8-8ff340e75592)

**Comment by sinclairpaul** [comment]
As part of the recent release of Node-Red the configuration was moved from what was then seen externally as the "config" folder, to an addon specific folder.  The configuration was migrated automatically but this would have only included anything in the "node-red" folder.  This was done primarily so that the addon backups would contain all of it's information, which previously didn't occur.

The container mounts folders from the file system, within the container itself, these do not need to match the folder names on the filesystem.

What is now presented in the local /config folder is available via other addons such as SMB/SSH/VSCode as /addon_configs/a0d7b954_nodered.  The original /config folder that was referenced is now mounted as /homeassistant.

As your files are specific to Node Red flows I would suggest that you move them to the /addon_configs/a0d7b954_nodered folder, to which they then should be accessible.

The reason it works from the SSH addon, as there was a link added for backwards compatibility as the addon does not require it's own data folder.

**Comment by matata86** [comment]
Works great. Thank you!
