### ISSUE TITLE
Lost Server after OS update

### ISSUE THREAD

**Issue by radionerd1** [hassio-addons/addon-node-red#1786]
# Problem/Motivation

Updated Home Assistant OS 11.3

## Expected behavior
Node-Red Flows should continue to work
## Actual behavior
All flows are stopped and in red, unknown, missing:
Lost server
api-call-service
server-state-changed
 ha-fire-event

I was one of the guys that had trouble with the last node red update.

`
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 16.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.3  (aarch64 / odroid-n2)
 Home Assistant Core: 2024.1.0
 Home Assistant Supervisor: 2023.12.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nginx successfully started

up to date, audited 245 packages in 3s

44 packages are looking for funding
  run `npm fund` for details

8 moderate severity vulnerabilities

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[00:53:55] INFO: Starting Node-RED...

> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js

5 Jan 00:53:58 - [info] 

Welcome to Node-RED
===================

5 Jan 00:53:58 - [info] Node-RED version: v3.1.0
5 Jan 00:53:58 - [info] Node.js  version: v18.18.2
5 Jan 00:53:58 - [info] Linux 6.1.70-haos arm64 LE
5 Jan 00:53:59 - [info] Loading palette nodes
5 Jan 00:53:59 - [warn] [node-red-contrib-home-assistant-websocket] Node module cannot be loaded on this version. Requires: >=3.1.1 
5 Jan 00:54:01 - [info] Dashboard version 3.6.2 started at /endpoint/ui
5 Jan 00:54:02 - [info] Settings file  : /etc/node-red/config.js
5 Jan 00:54:02 - [info] Context store  : 'default' [module=memory]
5 Jan 00:54:02 - [info] User directory : /config/
5 Jan 00:54:02 - [warn] Projects disabled : editorTheme.projects.enabled=false
5 Jan 00:54:02 - [info] Flows file     : /config/flows.json
5 Jan 00:54:02 - [info] Server now running at http://127.0.0.1:46836/
5 Jan 00:54:03 - [info] Waiting for missing types to be registered:
5 Jan 00:54:03 - [info]  - server
5 Jan 00:54:03 - [info]  - api-call-service
5 Jan 00:54:03 - [info]  - server-state-changed
5 Jan 00:54:03 - [info]  - api-current-state
5 Jan 00:54:03 - [info]  - ha-fire-event
[00:54:03] INFO: Starting NGinx...`

**Comment by Hans-chr2** [comment]
Same for me, i lost all the "Home Assistant nodes" 

### ******* HA info ********
Home Assistant

    Core 2024.1.1
    Supervisor 2023.12.0
    Operating System 11.3
    Brugerflade 20240104.0

### **_NodeRed info *_**
Welcome to Node-RED
===================

5 Jan 19:04:44 - [info] Node-RED version: v3.1.0
5 Jan 19:04:44 - [info] Node.js  version: v18.18.2
5 Jan 19:04:44 - [info] Linux 6.1.70-haos x64 LE
5 Jan 19:04:44 - [info] Loading palette nodes
5 Jan 19:04:44 - [warn] [node-red-contrib-home-assistant-websocket] Node module cannot be loaded on this version. Requires: >=3.1.1 
5 Jan 19:04:45 - [info] Dashboard version 3.6.2 started at /endpoint/ui
5 Jan 19:04:46 - [info] Settings file  : /etc/node-red/config.js
5 Jan 19:04:46 - [info] Context store  : 'default' [module=memory]
5 Jan 19:04:46 - [info] User directory : /config/
5 Jan 19:04:46 - [warn] Projects disabled : editorTheme.projects.enabled=false
5 Jan 19:04:46 - [info] Flows file     : /config/flows.json
5 Jan 19:04:46 - [info] Server now running at http://127.0.0.1:46836/
5 Jan 19:04:46 - [info] Waiting for missing types to be registered:
5 Jan 19:04:46 - [info]  - server
5 Jan 19:04:46 - [info]  - ha-device-config
5 Jan 19:04:46 - [info]  - ha-entity-config
5 Jan 19:04:46 - [info]  - api-call-service
5 Jan 19:04:46 - [info]  - server-state-changed
5 Jan 19:04:46 - [info]  - api-current-state
5 Jan 19:04:46 - [info]  - ha-sensor
5 Jan 19:04:46 - [info]  - poll-state
5 Jan 19:04:46 - [info]  - ha-switch
5 Jan 19:04:46 - [info]  - ha-device
[19:04:46] INFO: Starting NGinx...

**Comment by brunotfr** [comment]
Same for me:

**NodeRed info**
Flows stopped due to missing node types.

server
server-state-changed
api-call-service
api-current-state
server-events
ha-wait-until

**Log**
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 16.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.3  (amd64 / qemux86-64)
 Home Assistant Core: 2023.12.4
 Home Assistant Supervisor: 2023.12.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nginx successfully started

up to date, audited 146 packages in 2s

17 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (2 moderate, 2 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[20:42:46] INFO: Starting Node-RED...

> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js

5 Jan 20:42:49 - [info] 

Welcome to Node-RED
===================

5 Jan 20:42:49 - [info] Node-RED version: v3.1.0
5 Jan 20:42:49 - [info] Node.js  version: v18.18.2
5 Jan 20:42:49 - [info] Linux 6.1.70-haos x64 LE
5 Jan 20:42:50 - [info] Loading palette nodes
5 Jan 20:42:51 - [warn] [node-red-contrib-home-assistant-websocket] Node module cannot be loaded on this version. Requires: >=3.1.1 
5 Jan 20:42:52 - [info] Dashboard version 2.29.3 started at /endpoint/ui
5 Jan 20:42:54 - [info] Settings file  : /etc/node-red/config.js
5 Jan 20:42:54 - [info] Context store  : 'default' [module=memory]
5 Jan 20:42:54 - [info] User directory : /config/
5 Jan 20:42:54 - [warn] Projects disabled : editorTheme.projects.enabled=false
5 Jan 20:42:54 - [info] Flows file     : /config/flows.json
5 Jan 20:42:54 - [info] Server now running at http://127.0.0.1:46836/
5 Jan 20:42:54 - [info] Waiting for missing types to be registered:
5 Jan 20:42:54 - [info]  - server
5 Jan 20:42:54 - [info]  - server-state-changed
5 Jan 20:42:54 - [info]  - api-call-service
5 Jan 20:42:54 - [info]  - api-current-state
5 Jan 20:42:54 - [info]  - server-events
5 Jan 20:42:54 - [info]  - ha-wait-until
[20:42:54] INFO: Starting NGinx...

**Comment by brunotfr** [comment]
Adding 'node-red-contrib-home-assistant-websocket'  in NodeRed via -> Manage palette -> install does fix the issue temporarily until you restart the NodeRed addon.

Welcome to Node-RED
===================

6 Jan 12:32:56 - [info] Node-RED version: **v3.1.0**
6 Jan 12:32:56 - [info] Node.js  version: v18.18.2
6 Jan 12:32:56 - [info] Linux 6.1.63-haos x64 LE
6 Jan 12:32:56 - [info] Loading palette nodes
6 Jan 12:32:59 - [warn] [node-red-contrib-home-assistant-websocket] Node module cannot be loaded on this version. Requires: >=**3.1.1**

**Comment by radionerd1** [comment]
Wow,
My lights and automatons started working after adding 'node-red-contrib-home-assistant-websocket' in NodeRed via -> Manage palette -> install does fix the issue temporarily until you restart the NodeRed addon.

**Comment by radionerd1** [comment]
@frenck 
Help us, Obi-Wan Kenobi; You’re our Only Hope!

Please, when you get a chance Frenk, Jeti Knight ;-)

**Comment by Baxxy13** [comment]
Just downgrade node-red-contrib-home-assistant-websocket to 0.60.1 (which ist the latest v3.1.0 compatible version)
DL: [node-red-contrib-home-assistant-websocket-0.60.1.tgz](https://registry.npmjs.org/node-red-contrib-home-assistant-websocket/-/node-red-contrib-home-assistant-websocket-0.60.1.tgz) and upload via palette-manager / installation

**Comment by frenck** [comment]
# ℹ️ One should not be managing the WebSocket node manually.

The add-on will revert this change each time as well.

Please update to v17.0.0 of the add-on instead.
