### ISSUE TITLE
Issues with WebSocket above 0.59.0

### ISSUE THREAD

**Issue by pdecker414** [hassio-addons/addon-node-red#1831]
# Problem/Motivation

I am not able to use Websocket above 0.59.0. If I do it shows NodeRed unable to communicate with Home assistant after restart. If I downgrade Websocket back to 0.59.0 communication is restored. Yes I rebooted each time.

HASOS
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 17.0.7
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.5  (amd64 / qemux86-64)
 Home Assistant Core: 2024.2.1
 Home Assistant Supervisor: 2024.01.1

It is the same issue reported under the following link.
https://community.home-assistant.io/t/warning-do-not-update-websocket-to-0-61-1-with-add-on-version-16-0-2/653887
(Unknown: api-call-service)
I can provide any other information on request.

**Comment by julianrinaldi** [comment]
I've been having the same issue, and have the same system setup as you. I can get Node Red working on a different machine (MacOS) even with 0.63.0 and it connects fine and works, but is very limiting. Even if I downgrade to 0.59.0 on my Home Assistant OS install, I can't get it to work, even after restarting, etc. It says it's connected to http://supervisor/core, but no service or entities will show up when trying to make a flow. If I put in the server information manually instead of choosing the "Using the Home Assistant Add-on" option, it also says it is connected in the logs, but it still doesn't work. Very frustrated by this.
