### ISSUE TITLE
vs NotoriousBDG Node-Red

### ISSUE THREAD

**Issue by eantonya** [hassio-addons/addon-node-red#2]
Before this Node-Red was provided by NotoriousBDG hassio repo.

How does this implementation compare vs NotoriousBDG?
Should one move from NotoriousBDG to this?
If the answer is yes - how does one port existing automations to this implementation?

**Comment by frenck** [comment]
Hi there @eantonya,

In, we use GitHub for bug and feature tracking. For support questions, I generally would advise using the Community Forum, Reddit or Discord channels.

I've written an extensive reply on the differences on Reddit since I was asked the same question there:

https://www.reddit.com/r/homeassistant/comments/8nzabp/community_hassio_addon_nodered/dzzp62h/

Should you move? I'm not answering that. It is like asking Coca-Cola: "Should I drink Cola or Pepsi?".

You can move existing automations, this is discussed in the Reddit thread, linked above. Summary: Open your `/shares/flows.json` in an editor, copy its contents onto your clipboard. Go into the other Node-RED add-on interface, in the menu go to -> Import -> From Clipboard. Paste.
