### ISSUE TITLE
FirewallD doesn't play nice with Docker, 502 Bad Gateway

### ISSUE THREAD

**Issue by arretx** [hassio-addons/addon-node-red#291]
# Problem/Motivation

> NodeRED installed in Ubuntu with Docker experiences 502 Bad Gateway if FirewallD is running.

## Expected behavior

> NodeRED should load via ingress.

## Actual behavior

> 502 Bad Gateway

## Steps to reproduce

> Install HASS.io on Ubuntu in a Docker container via Frenck's script.

## Proposed changes

> I have no idea how to fix this, but it took me forever to finally figure out the connection between Docker and FirewallD (probably because of my experience level.)  ;)

**Comment by frenck** [comment]
This is not an add-on issue since well, the add-on uses the infrastructure given by Hass.io.

To answer your question a bit more, Hass.io uses an internal/separate Docker network to communicate between containers. If you block communications with a firewall, yeah sure, things will break. I don't see how that is an issue of our eco system.
