### ISSUE TITLE
npm_packages or node_packages

### ISSUE THREAD

**Issue by mcfrojd** [hassio-addons/addon-node-red#3]
# Problem/Motivation
When i install the node-red addon i get "npm_packages" in the config, but in your repo and examples it seem to be named "node_packages"
Might be the same, but could confuse some users (like me) :-) 

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Thanks, @mcfrojd! 

I agree there is a problem there. I started out with `node`, since Node-RED calls its packages `nodes`, nevertheless, I learned that additional NPM might be useful as well and since they are actually the same... I've renamed them during the development process.

So I guess I missed a spot! Thank you for letting me know.

**Comment by frenck** [comment]
Fixed in the `master` branch, will be generally available in the next release.

Thanks again @mcfrojd 👍
