### ISSUE TITLE
current state node doesn't work if preceded by an events: all node

### ISSUE THREAD

**Issue by stefanlod** [hassio-addons/addon-node-red#575]
# Problem/Motivation

The `current state` node is essential for constructing flows with differing conditions. If it doesn't work properly for all scenarios, its usefulness is limited.

## Expected behavior

When receiving a message from the `events: all` node, the `current state` node should be able to query the relevant conditions in Home Assistant and provide either a positive or negative answer. This is the standard behaviour that is seen from other nodes, such as `trigger: state`.

## Actual behavior

When receiving the message from `events: all` node, the `current state` node doesn't properly query anything and always fails.

## Steps to reproduce

In my particular flow, I've got an `events: all` node that listens for events from `zwave.scene_activated`. That is connected to a `current state` node that checks for whether a light is on or not.

## Proposed changes

If you don't have any specific actions tied to a fail, you can swap out the `current state` node for a `wait until` node with a very short timeout.

**Comment by frenck** [comment]
Hi there @stefanlod!

Thanks for opening up an issue. However, add-ons wrap existing applications, in this case, Node-RED and its nodes. It seems like your issue is with the Home Assistant Node for Node-RED.

Please report your issue here:

<https://github.com/zachowj/node-red-contrib-home-assistant-websocket>

Thanks! 👍
