### ISSUE TITLE
Addon doesn't start

### ISSUE THREAD

**Issue by damiano75** [hassio-addons/addon-node-red#825]
# Problem/Motivation
Home Assistant 2020.12.1, Supervisor Version 2020.12.7, Operating System Home Assistant OS 5.9 on a RPi 3, Addon doesn't start

## Actual behavior
In the addon log: 
if: fatal: unable to spawn s6-rmrf: Exec format error

**Comment by jaycrossler** [comment]
Got the same:

```
24 Dec 10:15:57 - [info] Server now running at http://127.0.0.1:46836/
24 Dec 10:15:57 - [info] Starting flows
24 Dec 10:15:57 - [info] Started flows
24 Dec 10:15:57 - [red] Uncaught Exception:
24 Dec 10:15:57 - Error: bind EADDRINUSE 0.0.0.0:1900
    at dgram.js:338:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! addon-node-red@ start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-24T15_15_57_446Z-debug.log
[10:15:57] INFO: Starting Node-RED...
```

**Comment by frenck** [comment]
These are 2 different issues. Please @jaycrossler, never ever stack issues, anywhere on any issue tracker. The error reported in this issue, does not even remotely occur in your report. So, please separate. Thanks 👍 


@damiano75 
> if: fatal: unable to spawn s6-rmrf: Exec format error

This seems like an architecture mixup. Since the add-on hasn't able to run, there isn't much I can do from an add-on perspective. Please report your issue upstream with the Home Assistant project (probably the Supervisor or OS).

@jaycrossler 
`24 Dec 10:15:57 - Error: bind EADDRINUSE 0.0.0.0:1900`

You have installed something that wants to use port 1900, but port 1900 is already in use by something else you've installed. I cannot tell what exactly is using that from that message, but since you've installed it yourself, I guess you know best.

**Comment by jaycrossler** [comment]
Thanks, and sorry for cluttering.

I actually fixed my issue by deleting the node-red directory and reinstalling.  It looks like a node-red plugin update caused my issue - agreed, wasn't the same issue as the one above.
