### ISSUE TITLE
Two networks issues

### ISSUE THREAD

**Issue by dsduarte** [hassio-addons/addon-node-red#895]
# Problem/Motivation
So... I have a hassio running on a VM on a QNAP NAS. I have two segmented networks and the QNAP has one ethernet port attached to each segment of my network. All my amazon echo devices are attached to one of those networks and I'm having trouble with some nodes like node-red-contrib-wemo-emulator and node-red-contrib-alexa-local. After I set up a local node, is expected to go to alexa app and discover new devices. Some times alexa can't find those nodes and it only finds when I disable one ethernet connection and restart hassio.
> (Why the issue was filed)
I can't find any option to bind node-red or the local nodes to a dedicated interface.
## Expected behavior
The local nodes able to communicate with echo devices.

**Comment by frenck** [comment]
From an add-on perspective, there is not much I can do. Please report this issue with the node you've mentioned, as those need to be able to handle that.

As in more general advice, when using multiple networks in this world of IoT, it is easier to keep a single interface on your server, while routing the appropriate traffic over the multiple VLANs. For example, by using IGMP proxies and mDNS repeaters/reflectors. Simply because there are many pieces of software out there, that don't handle multiple interfaces correctly.
