### ISSUE TITLE
Unable to start the add-on (8.2.1) on RPi

### ISSUE THREAD

**Issue by unicode8** [hassio-addons/addon-node-red#956]
# Problem/Motivation
Updated the add-on to 8.2.1.  It does not start.

## Expected behavior
On update the add-on should start

## Actual behavior
Here is content of the log.

Add-on version: 8.2.1
You are running the latest version of this add-on.
System: Home Assistant OS 5.12  (armv7 / raspberrypi3)
Home Assistant Core: 2021.3.4
Home Assistant Supervisor: 2021.03.6

patching file nodes/ui_base.html
Hunk #1 succeeded at 1160 (offset 629 lines).
/var/run/s6/etc/cont-init.d/node-red.sh: line 83:   431 Illegal instruction     (core dumped) npm uninstall node-red-contrib-home-assistant node-red-contrib-home-assistant-llat node-red-contrib-home-assistant-ws
[20:30:14] FATAL: Failed un-installing conflicting packages
[cont-init.d] node-red.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

## Steps to reproduce
This happens when trying to restart the add-on

**Comment by HypoxiaSE** [comment]
+1 on this behavior, I have the same experience when upgrading from 7.2.11.

**Comment by sinclairpaul** [comment]
Please post the addon config, and the contents of the config\node-red\package.json file (in the HA config folder)

**Comment by HypoxiaSE** [comment]
I've rolled back to 7.2.11 and don't have access to the 8.2.1 setup as of know.
Posting the content before the upgrade which hopefully will give enough hints.

**Config:**
credential_secret: ************
dark_mode: false
http_node:
  username: ''
  password: ''
http_static:
  username: ''
  password: ''
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
require_ssl: false
system_packages: []
npm_packages: []
init_commands: []

**config\node-red\package.json**
{
    "name": "node-red-project",
    "description": "A Node-RED Project",
    "version": "0.0.1",
    "private": true,
    "dependencies": {
        "@fetchbot/node-red-contrib-ikea-home-smart": "~0.3.2",
        "node-red-contrib-boolean-logic-ultimate": "~1.0.12",
        "node-red-contrib-cast": "~0.2.16",
        "node-red-contrib-castv2": "~3.2.8",
        "node-red-contrib-config": "~1.1.3",
        "node-red-contrib-deconz": "~1.2.0",
        "node-red-contrib-google": "~0.2.0",
        "node-red-contrib-google-calendar": "~0.1.2",
        "node-red-contrib-google-home-notify": "0.0.7",
        "node-red-contrib-home-assistant-websocket": "~0.27.7",
        "node-red-contrib-ical-events": "~0.17.1",
        "node-red-contrib-light-scheduler": "0.0.16",
        "node-red-contrib-shelly": "~1.5.3",
        "node-red-contrib-sun-position": "~1.1.7",
        "node-red-contrib-sunevents": "~2.0.3",
        "node-red-contrib-verisure": "~0.4.1",
        "node-red-dashboard": "~2.24.2"
    }
}

**Comment by sinclairpaul** [comment]
The issue here is that you have likely upgraded the pallettes in the app

"node-red-contrib-home-assistant-websocket": "~0.27.7",

You should really add the additional npm packages in the config to avoid these issues.

**Comment by HypoxiaSE** [comment]
@sinclairpaul Thanks for the hint!

I didn't want to touch /config/node-red/package.json as I have made no manual additions to this file at all. The content of the file has always been automagically maintained by NodeRed.

I simply updated my entire palette before upgrading to 8.2.1 and that seem to have solved the issue. For node-red-contrib-home-assistant-websocket it was upgraded from the existing 0.27.7 to 0.30.1.
However, when restarting after update to 8.2.1, I still had the old palette configuration installed (i.e. the configuration before the upgrade from e.g. 0.27.7 to 0.30.1). Also, the content of /config/node-red/package.json was still unchanged.
Even so, NR 8.2.1 was able to be started.

After the successful update to 8.2.1 I repeated the palette update which also turned out to be successful and led to updated contents of /config/node-red/package.json.

Finally running both 8.2.1 and the latest available versions of my palette components. I haven't verified that all the code is still working as expected, but that's a more classic NodeRed palette upgrade test process :)
